//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNotification
    {
        public System.Guid CustomerNotificationID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsSeen { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
