//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public System.Guid Id { get; set; }
        public System.Guid CategoryId { get; set; }
        public Nullable<System.Guid> ConditionId { get; set; }
        public Nullable<System.Guid> ConditionDeviceId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public int SequenceNumber { get; set; }
    
        public virtual FAQ_Categories FAQ_Categories { get; set; }
        public virtual FAQ_Category_Condition FAQ_Category_Condition { get; set; }
        public virtual FAQ_Category_Condition_Device FAQ_Category_Condition_Device { get; set; }
    }
}
