//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_Category_Condition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAQ_Category_Condition()
        {
            this.FAQs = new HashSet<FAQ>();
            this.FAQ_Category_Condition_Device = new HashSet<FAQ_Category_Condition_Device>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CategoryId { get; set; }
        public string ConditionCode { get; set; }
        public string ConditionName { get; set; }
        public bool IsActive { get; set; }
        public short SequenceNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAQ> FAQs { get; set; }
        public virtual FAQ_Categories FAQ_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAQ_Category_Condition_Device> FAQ_Category_Condition_Device { get; set; }
    }
}
