//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpTicket
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClientId { get; set; }
        public System.Guid CategoryId { get; set; }
        public string Query { get; set; }
        public bool SendEmailCopy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public Nullable<System.Guid> EmailHistoryId { get; set; }
        public int ReferenceNumber { get; set; }
        public short QueryStatus { get; set; }
        public short QuerySource { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string PostCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string NHSNumber { get; set; }
        public string AdvisorNotes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Email { get; set; }
    }
}
