//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlTemplate
    {
        public System.Guid ID { get; set; }
        public string Key { get; set; }
        public string HTMLColumn { get; set; }
        public string Orignal { get; set; }
        public string Title { get; set; }
        public string FromName { get; set; }
        public string FromEmail { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> IsBulk { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public bool IsActive { get; set; }
    }
}
