//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orders_Detail = new HashSet<Orders_Detail>();
            this.Orders_History = new HashSet<Orders_History>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CartId { get; set; }
        public decimal Amount { get; set; }
        public decimal VAT { get; set; }
        public decimal TotalAmount { get; set; }
        public string Currency { get; set; }
        public short OrderStatus { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string OrderNumber { get; set; }
        public string OrderTrackingNumber { get; set; }
        public Nullable<System.Guid> DiscountVoucherId { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
    
        public virtual DiscountVoucher DiscountVoucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Detail> Orders_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_History> Orders_History { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
