//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.ReturnRequests = new HashSet<ReturnRequest>();
        }
    
        public System.Guid OrderDetailID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<float> Discount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Fulfilled { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.Guid> ShipperID { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnRequest> ReturnRequests { get; set; }
        public virtual Product Product { get; set; }
    }
}
