//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnRequest
    {
        public System.Guid ReturnRequestID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.Guid> OrderDetailID { get; set; }
        public Nullable<System.Guid> Status { get; set; }
        public Nullable<System.Guid> ShipperID { get; set; }
        public string ReturnReason { get; set; }
        public Nullable<bool> Fullfilled { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
