//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCart()
        {
            this.Orders = new HashSet<Order>();
            this.ShoppingCart_Detail = new HashSet<ShoppingCart_Detail>();
            this.ShoppingCart_Registration = new HashSet<ShoppingCart_Registration>();
        }
    
        public System.Guid Id { get; set; }
        public decimal Amount { get; set; }
        public decimal VAT { get; set; }
        public decimal TotalAmount { get; set; }
        public string Currency { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> ClientId { get; set; }
        public Nullable<System.Guid> DiscountVoucherId { get; set; }
    
        public virtual DiscountVoucher DiscountVoucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_Detail> ShoppingCart_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_Registration> ShoppingCart_Registration { get; set; }
    }
}
