//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBusinessInformation
    {
        public System.Guid BusinessInfoID { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string BusinessExperience { get; set; }
        public string BusinessType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ProductType { get; set; }
        public string Website { get; set; }
        public string PaymentMethods { get; set; }
        public string BusinessEmail { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
