//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBusinessInformation
    {
        public System.Guid BusinessInfoID { get; set; }
        public System.Guid SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string BusinessExperience { get; set; }
        public string BusinessType { get; set; }
        public string Gender { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
