//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultivendorEcommerceStore.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public System.Guid UserMessageID { get; set; }
        public string Message { get; set; }
        public Nullable<int> MessageFrom { get; set; }
        public Nullable<int> MessageTo { get; set; }
        public Nullable<System.Guid> ConversationID { get; set; }
    }
}
